#!/bin/bash

echo "🚀 Excel Comparison Tool Deployment Package Ready!"
echo ""
echo "📁 Files included:"
echo "  ✅ excel_comparison.py (main app)"
echo "  ✅ requirements.txt (dependencies)"
echo "  ✅ runtime.txt (Python version)"
echo "  ✅ Procfile (start command)"
echo "  ✅ DEPLOYMENT_COMPARISON_TOOL.md (deployment guide)"
echo ""
echo "🎯 Next Steps:"
echo "1. Go to https://railway.app"
echo "2. Create a new project"
echo "3. Upload all files from this folder"
echo "4. Add environment variable: MAIN_APP_URL=https://web-production-9e92a.up.railway.app/"
echo "5. Deploy and get your comparison tool URL"
echo "6. Update the main app with the new comparison tool URL"
echo ""
echo "📖 See DEPLOYMENT_COMPARISON_TOOL.md for detailed instructions"
